name: titanic_platzi
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - jupyter
  - jupyterlab
  - kaggle
  - keras
  - lightgbm
  - matplotlib
  - missingno
  - nbdime
  - numpy
  - pandas
  - pandas-flavor
  - pandas-profiling > 1.4.1
  - pip
  - plotly
  - pyjanitor
  - pylint
  - pyspark
  - python=3.7
  - python-dotenv
  - python-graphviz
  - scikit-learn
  - seaborn
  - shap
  - statsmodels
  - tensorflow
  - xgboost
  - pip:
    - h2o
    - pyhere